### ISSUE TITLE
[Question] Would a video a couple of minutes long do for training?

### ISSUE THREAD

**Issue by rraallvv** [artifacia/Super-Resolution#2]
I have a bunch of videos, each a couple of minutes long, that I want to enhance. I can obtain the separate images for each frame using FFMPEG and feed those images to your script.

So my questions is whether using just a single high quality video would suffice to train the network?

All the videos are the same take of the lower region of someone's face (nose and lips) where the person is pronouncing some words.

Keep up the good work.

**Comment by Vgandhi9** [comment]
You can definitely give it a try, but you may face issues in generalizations. For better results, you can increase the training data size.
Glad you like our work.

**Comment by rraallvv** [comment]
@Vgandhi9 thanks! I'll give it a try.
